### PR TITLE
Add Connection::create_native_widget_from_rwh()

### LINKED ISSUE #60: Provide a Way to Create a NativeWidget From a Raw Window Handle
Would you be open to a PR for a `NativeWidget::from_raw_window_handle` that could take a [`&impl HasRawWindowHandle`](https://docs.rs/raw-window-handle/0.3.3/raw_window_handle/trait.HasRawWindowHandle.html).

It would essentially be an alternative to `NativeWidget::from_winit_window`.

---

I'm trying to get `surfman` to work for creating contexts and surfaces for `gfx-backend-gl` ( discussion here: https://github.com/gfx-rs/gfx/pull/3151. I haven't gotten the `surfman` code pushed yet ). I was going to put the code right in `gfx-backend-gl`, but I thought that it could be useful to others if it was included in `surfman`.

### PR DESCRIPTION
**Pull request by zicklag**
Adds a function for creating a native widget from a raw window handle.

Not tested yet.

Fixes #60.

### CODE REVIEW

**Comment by kvark** [comment]
Surfman doesn't support iOS platform?

**Comment by kvark** [comment]
Added macOS and Android in a sub-pr https://github.com/katharostech/surfman/pull/1

**Comment by zicklag** [comment]
Sweet, merged. :)

**Comment by zicklag** [comment]
@pcwalton So as far as the wayland implementation goes, I wasn't sure how to get the size of the wayland surface from the raw window handle, but according to this https://github.com/gfx-rs/gfx/pull/3151#issuecomment-604647849 there isn't really a real size to get.

I'm not sure if that will work fine then with an arbitrary size set at widget creation? Would the surface/widget need to be resized at swapchain creation time, or do we not need to worry about it? I don't know how to test Wayland so I haven't tested it.

**Comment by zicklag** [comment]
FYI I just added an extra commit in here that fixes builds on Linux that are made without the `sm-x11` feature.

I could split it to a separate PR if desired.

**Comment by zicklag** [comment]
Oops, that last commit was broken BTW, don't merge yet!

**Edit:** Actually, it wasn't broken. I was confused, but still don't merge this yet.

**Comment by zicklag** [comment]
Closing in favor of https://github.com/servo/surfman/pull/172.

**Pull request closed without merging**
